apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: murmur
resources:
  - namespace.yaml
  - nats.yaml
  - agent-config.example.yaml
  - agent-daemon.yaml
commonLabels:
  app.kubernetes.io/part-of: murmur-v2
